
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ipd
 */
public class AllInputs extends javax.swing.JFrame {

    /**
     * Creates new form AllInputs
     */
    public AllInputs() {
        initComponents();
        // center window on the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rbBelow18 = new javax.swing.JRadioButton();
        rb18to35 = new javax.swing.JRadioButton();
        rb36andup = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        cbCat = new javax.swing.JCheckBox();
        cbDog = new javax.swing.JCheckBox();
        cbOther = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        comboContinent = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        slTemperature = new javax.swing.JSlider();
        btRegisterMe = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name:");

        jLabel2.setText("Age:");

        buttonGroup1.add(rbBelow18);
        rbBelow18.setSelected(true);
        rbBelow18.setText("Below 18");

        buttonGroup1.add(rb18to35);
        rb18to35.setText("18-35");

        buttonGroup1.add(rb36andup);
        rb36andup.setText("36 and above");

        jLabel3.setText("Pets");

        cbCat.setText("cat");

        cbDog.setText("dog");

        cbOther.setText("others");

        jLabel4.setText("Continent of residence:");

        comboContinent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Europe", "Asia", "North America", "South America", "Central America", "Africa", "Australia and Oceania", "Antarctica" }));
        comboContinent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboContinentActionPerformed(evt);
            }
        });

        jLabel5.setText("Preferred temperature:");

        slTemperature.setMajorTickSpacing(5);
        slTemperature.setMaximum(35);
        slTemperature.setMinimum(15);
        slTemperature.setMinorTickSpacing(1);
        slTemperature.setPaintLabels(true);
        slTemperature.setPaintTicks(true);
        slTemperature.setSnapToTicks(true);

        btRegisterMe.setText("Register me");
        btRegisterMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterMeActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboContinent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(slTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbCat)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbDog)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbOther))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbBelow18)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb18to35)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb36andup)
                                        .addGap(82, 82, 82)
                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(btRegisterMe)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(rbBelow18)
                                    .addComponent(rb18to35)
                                    .addComponent(rb36andup)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbCat)
                            .addComponent(cbDog)
                            .addComponent(cbOther))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(comboContinent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel5))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRegisterMe)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboContinentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboContinentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboContinentActionPerformed

    private void btRegisterMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterMeActionPerformed
        String name = tfName.getText();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "You forgot to enter your name",
                    "Name missing",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        //
        AgeRange age;
        if (rbBelow18.isSelected()) {
            age = AgeRange.Below18;
        } else if (rb18to35.isSelected()) {
            age = AgeRange.From18to35;
        } else if (rb36andup.isSelected()) {
            age = AgeRange.From36upward;
        } else {
            JOptionPane.showMessageDialog(this,
                    "Unknown radio box selection",
                    "Internal error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        //
        ArrayList<String> pets = new ArrayList<>();
        if (cbCat.isSelected()) {
            pets.add("cat");
        }
        if (cbDog.isSelected()) {
            pets.add("dog");
        }
        if (cbOther.isSelected()) {
            pets.add("other");
        }
        //
        String continent = (String) comboContinent.getSelectedItem();
        //
        int temperature = slTemperature.getValue();
        //
        String petList = "";
        for (String p : pets) {
            if (petList.equals("")) {
                petList = p;
            } else {
                petList += "," + p;
            }
        }
        System.out.printf("%s;%s;%s;%s;%s\n",
                name, age, petList, continent, temperature);
    }//GEN-LAST:event_btRegisterMeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllInputs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllInputs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllInputs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllInputs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllInputs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegisterMe;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbCat;
    private javax.swing.JCheckBox cbDog;
    private javax.swing.JCheckBox cbOther;
    private javax.swing.JComboBox<String> comboContinent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JRadioButton rb18to35;
    private javax.swing.JRadioButton rb36andup;
    private javax.swing.JRadioButton rbBelow18;
    private javax.swing.JSlider slTemperature;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
