
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ipd
 */
public class IceCream extends javax.swing.JFrame {
        File currentFile;
    /**
     * Creates new form IceCream
     */
    public IceCream() {
        initComponents();
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuItem3 = new javax.swing.JMenuItem();
        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        tfCustomerName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        rSmall = new javax.swing.JRadioButton();
        rMedium = new javax.swing.JRadioButton();
        rLarge = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        cChocolate = new javax.swing.JCheckBox();
        cOther = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btFalvor1 = new javax.swing.JButton();
        btFalvor2 = new javax.swing.JButton();
        btFalvor3 = new javax.swing.JButton();
        btFalvor4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miLoad = new javax.swing.JMenuItem();
        miSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miExit = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Customer Name");

        jLabel2.setText("Scoop Size");

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        jLabel3.setText("Orders");

        buttonGroup1.add(rSmall);
        rSmall.setText("Small");
        rSmall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSmallActionPerformed(evt);
            }
        });

        buttonGroup1.add(rMedium);
        rMedium.setText("Medium");

        buttonGroup1.add(rLarge);
        rLarge.setText("Large");

        jLabel4.setText("Toppings");

        cChocolate.setText("Chocolate");

        cOther.setText("Other");

        jLabel5.setText("Cone Type");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Waffle", "Other", "Bare Hands" }));

        jLabel6.setText("Flavors");

        btFalvor1.setText("Add1");
        btFalvor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFalvor1ActionPerformed(evt);
            }
        });

        btFalvor2.setText("Add2");
        btFalvor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFalvor2ActionPerformed(evt);
            }
        });

        btFalvor3.setText("add3");
        btFalvor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFalvor3ActionPerformed(evt);
            }
        });

        btFalvor4.setText("add4");
        btFalvor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFalvor4ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        miLoad.setText("Load Flavours");
        miLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLoadActionPerformed(evt);
            }
        });
        jMenu1.add(miLoad);

        miSave.setText("Save Order as");
        miSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSaveActionPerformed(evt);
            }
        });
        jMenu1.add(miSave);
        jMenu1.add(jSeparator1);

        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        jMenu1.add(miExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(tfCustomerName))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cChocolate)
                                    .addGap(10, 10, 10)
                                    .addComponent(cOther))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rSmall)
                                    .addGap(18, 18, 18)
                                    .addComponent(rMedium)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rLarge))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btFalvor1)
                        .addGap(18, 18, 18)
                        .addComponent(btFalvor2)
                        .addGap(24, 24, 24)
                        .addComponent(btFalvor3)
                        .addGap(18, 18, 18)
                        .addComponent(btFalvor4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rSmall)
                    .addComponent(rMedium)
                    .addComponent(rLarge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cChocolate)
                    .addComponent(cOther))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFalvor1)
                    .addComponent(btFalvor2)
                    .addComponent(btFalvor3)
                    .addComponent(btFalvor4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSaveActionPerformed
        JFileChooser fileChooser = new JFileChooser(); 
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            currentFile = fileChooser.getSelectedFile();
            if (fileChooser.getFileFilter() != fileChooser.getAcceptAllFileFilter()) {
                if (!currentFile.getName().toLowerCase().endsWith(".ORD")) {
                    currentFile = new File(currentFile.getAbsolutePath() + ".ORD");
                }
            }
            try (PrintWriter pw = new PrintWriter(currentFile)) {
                pw.write(jTextArea.getText());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(IceCream.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }//GEN-LAST:event_miSaveActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        dispose();
    }//GEN-LAST:event_miExitActionPerformed

    private void miLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLoadActionPerformed
        JFileChooser fileChooser = new JFileChooser(); 
        fileChooser.setFileFilter(new FileNameExtensionFilter("Text files (*.txt)", "txt"));
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
            //FileFilter filter = new FileNameExtensionFilter("Flavors Document","txt"); // should be Flav instead but txt is used to check if it works or not
            //fileChooser.setFileFilter(filter);
                currentFile = fileChooser.getSelectedFile();
               Scanner s = new Scanner(currentFile).useDelimiter("\n"); 
               btFalvor1.setText(s.next());
               btFalvor2.setText(s.next());
               btFalvor3.setText(s.next());
               btFalvor4.setText(s.next());
            } catch (IOException ex) {
                currentFile = null;
                JOptionPane.showMessageDialog(this,
                        "Unable to read file contents from " + currentFile.getAbsolutePath(),
                        "File access error",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_miLoadActionPerformed

    private void btFalvor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFalvor1ActionPerformed
        String name = tfCustomerName.getText();
        String Flavor = btFalvor1.getText();
        String msg = "Hi," + name + "Your Flavor is " + Flavor;
        jTextArea.setText(msg);
    }//GEN-LAST:event_btFalvor1ActionPerformed

    private void rSmallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSmallActionPerformed
        
    }//GEN-LAST:event_rSmallActionPerformed

    private void btFalvor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFalvor2ActionPerformed
        String name = tfCustomerName.getText();
        String Flavor = btFalvor2.getText();
        String msg = "Hi," + name + "Your Flavor is " + Flavor;
        jTextArea.setText(msg);
    }//GEN-LAST:event_btFalvor2ActionPerformed

    private void btFalvor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFalvor3ActionPerformed
        String name = tfCustomerName.getText();
        String Flavor = btFalvor3.getText();
        String msg = "Hi," + name + "Your Flavor is " + Flavor;
        jTextArea.setText(msg);
    }//GEN-LAST:event_btFalvor3ActionPerformed

    private void btFalvor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFalvor4ActionPerformed
        String name = tfCustomerName.getText();
        String Flavor = btFalvor4.getText();
        String msg = "Hi," + name + "Your Flavor is " + Flavor;
        jTextArea.setText(msg);
    }//GEN-LAST:event_btFalvor4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IceCream.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IceCream.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IceCream.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IceCream.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IceCream().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFalvor1;
    private javax.swing.JButton btFalvor2;
    private javax.swing.JButton btFalvor3;
    private javax.swing.JButton btFalvor4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cChocolate;
    private javax.swing.JCheckBox cOther;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miLoad;
    private javax.swing.JMenuItem miSave;
    private javax.swing.JRadioButton rLarge;
    private javax.swing.JRadioButton rMedium;
    private javax.swing.JRadioButton rSmall;
    private javax.swing.JTextField tfCustomerName;
    // End of variables declaration//GEN-END:variables
}
